---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/health":
    get:
      summary: API health check
      tags:
      - Health
      responses:
        '200':
          description: healthy
          content:
            application/json:
              schema:
                type: object
                required:
                - status
                properties:
                  status:
                    type: string
                    example: ok
servers:
- url: "/"
